project:
  type: website
  output-dir: docs

website:
  title: "Veda v jaskyni o.z"
  
  navbar:
    left:
      - href: index.qmd
        text: Domov
      - href: about.qmd
        text: O nás
      - href: news.qmd
        text: Novinky
      - href: team.qmd
        text: Ľudia
      - href: ourwork
        text: Realizácie
      - href: contact_us.qmd
        text: Kontakt

format:
  html:
    theme:
      - cyborg
      - brand
    css: styles.css
    toc: true
    page-layout: full

editor: visual

