---
title: "Pre študentov"
format: html
---

Tu nájdete vždy aktuálne informácie ohľadom podujatí, ktoré sa oplatí navštíviť, užitočné linky a niekedy aj príležitosti pre študentov (Bc., MSc., Mgr. alebo doktorandov), kde sa môžu uchádzať o finančnú podporu pre účasť na podujatí.

## Aktuálne

Veda v jaskyni o. z. vyčlenila prostriedky na úhradu časti účastníckeho poplatku [Medzinárodnej letnej školy biospeleológie](https://biogeo.ubbcluj.ro/pages/taxonomie/?page_id=138146&lang=en).

## Podmienky uchádzania sa o podporu

1. Uchádzač musí byť študentom bakalárskeho, magisterského alebo doktorandského stupňa na univerzite na Slovensku (v roku 2026 aj s pokračovaním v roku 2027), na požiadanie sa preukáže relevantnými dokladmi.
2. Uchádzač sa prihlási prostredníctvom [online formulára](https://forms.gle/MeZVzmUyvx6v3LDW6).
3. Podporený účastník alebo podporená účastníčka napíše krátky článok o účasti na podujatí a svojich skúsenostiach do Spravodaja Slovenskej speleologickej spoločnosti v rámci roku 2026 (deadline na zaslanie článku september 2026).

Prihlasujte sa do **10. 07. 2026** a Vaše otázky zodpovieme na <vedavjaskyni@gmail.com>.
