---
title: "Realizácie"
format: html
---

Veda v jaskyni o.z. realizuje okrem výskumu i rôzne aktivity pre verejnosť, so zameraním najmä na vzdelávanie a ochranu životného prostredia. Nižšie uvádzame zoznam a detaily o našich realizáciách.
[Podporte nás v ďalších projektoch!](contact_us.qmd#podporte-nas)

::: {collapse="true"}
<details>
  <summary><h2>Výstava v Ekocentre</h2></summary>
  <p>V priestoroch [Ekocentra Stupava](https://www.facebook.com/ekocentrumstupava/?locale=sk_SK) sme vytvorili malú náučnú inštaláciu s témou "Vznik a vývoj jaskýň", kde populárnou formou prezentujeme aktuálne vedecké poznatky o vzniku a vývoji jaskynných priestorov, tvorbe sintrovej výsdoby a jej vyžiteľnosti pre vedecký výskum, ako aj relevantnosti jaskýň pre archeologický výskum. Vystavené exponáty pochádzajú dominantne z oblasti neďalekého Borinského krasu. Výstavu sme zrealizovali v spolupráci s jaskyniarskym klubom [Speleo Bratislava](https://speleobratislava.sk/), ktorého prieskumné územie je práve Borinský kras. Umelecké fotografie do výstavy poskytol jaskynný fotograf a potápač [Michal Ševeček](https://sevecek.portfoliobox.net/).

**Galéria** 

**O výstave** 

Výstava je trvalou inštaláciou, môžete ju navštíviť vždy počas otváracích hodín Ekocentra - v stredy a soboty 10:00 – 17:00.</p>
</details>

:::

::: {collapse="true"}
<details>
  <summary><h2>Kryštálová jaskyňa</h2></summary>
  <p>Kryštáľová jaskyňa pod Rozsutcom je verejnosti neprístupná lokalita v správe jaskyniarskej skupiny [Adama Vallu](https://www.terchova.sk/vsetky-clanky/obec/obecne-organizacie/jaskyniarska-skupina-a-vallu-mala-fatra-sever). Vedecký výskum v Kryštálovej jaskyni realizujeme v spolupráci s miestnymi jaskyniarmi, Ústavom vied o Zemi v Banskej Bystrici, a dvoma zahraničnými pracoviskami: [Quaternary research group](https://quaternary.uibk.ac.at/) z Innsbrucku a [IKER](https://iker.atomki.hu/en/about-us/) centrom enviromntálnych vied a izotopovej klimatológie. 

Kryštálová jaskyňa je unikátnou lokalitou, ktorá nám môže poskytnúť informácie o histórii hydrologického a klimatického režimu v oblasti. Pre jej ochranu nie je sprístupnená, a práve preto sme pre Vás vytvorili jej virtuálnu prehliadku, ktorú si si môžete pozrieť[TU](https://vtc.virtualtourscreator.com.au/share/20499d11c5d9922adcc23603c1341f0f).

Prvé výsledky výskumu si môžete prečítať tu: [Sevcikova et al. 2023](https://meetingorganizer.copernicus.org/EGU23/EGU23-2915.html).</p>
</details>
:::

::: {collapse="true"}
<details>
  <summary><h2>Exkurzie</h2></summary>
  <p>Záujemcom poskytujeme náučné exkurzie s prírodovednou tematikou. Exkurzie sa konajú vždy na zaujímavej lokalite a vítaní sú ľudia všetkých vekových kategórií. Našími najobľúbenejšími témami sú jaskyne, ich vznik a význam pre vedu; ale radi rozprávame i o vode, ochrane vôd v krasových územiach, alebo o iných environmentálnych témach. 
  Na exkurziách spolupracujeme so Speleo Bratislava a Ekocentrom Stupava, s ktorými sme zrealizovali niekoľko náučných exkurzií Borinským krasom.

**Galéria exkurzie Ekocentrum**


</p>
</details>
:::

